blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question or General Feedback
url: https://github.com/<your-repo>/discussions
    about: Use GitHub Discussions to ask questions or provide general feedback.
